### Trigger classification workflow when webhook is received
#POST http://localhost:8000/webhook
#POST https://app-jira-ticket-webhook-demo.azurewebsites.net/webhook
POST https://prod-31.swedencentral.logic.azure.com:443/workflows/b50b71d8f71e44cba5dde133e7e6851c/triggers/When_an_HTTP_request_is_received/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2FWhen_an_HTTP_request_is_received%2Frun&sv=1.0&sig=z5gr7dFyO0kiys-5RCKXpU58Q0I_DJ-sNdbepURfAsU
Content-Type: application/json

{
  "timestamp": 1773482733452,
  "webhookEvent": "jira:issue_created",
  "issue_event_type_name": "issue_created",
  "user": {
    "self": "https://hosseinzahed.atlassian.net/rest/api/2/user?accountId=712020%3A0e19ca7f-286b-4b22-9d55-a1afb44ccecd",
    "accountId": "712020:0e19ca7f-286b-4b22-9d55-a1afb44ccecd",
    "avatarUrls": {
      "48x48": "https://secure.gravatar.com/avatar/f2641f1938ab5186db38aadc22ea8be5?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHZ-5.png",
      "24x24": "https://secure.gravatar.com/avatar/f2641f1938ab5186db38aadc22ea8be5?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHZ-5.png",
      "16x16": "https://secure.gravatar.com/avatar/f2641f1938ab5186db38aadc22ea8be5?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHZ-5.png",
      "32x32": "https://secure.gravatar.com/avatar/f2641f1938ab5186db38aadc22ea8be5?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHZ-5.png"
    },
    "displayName": "Hossein Zahed",
    "active": true,
    "timeZone": "Europe/Copenhagen",
    "accountType": "atlassian"
  },
  "issue": {
    "id": "10069",
    "self": "https://hosseinzahed.atlassian.net/rest/api/2/issue/10069",
    "key": "GTS-5",
    "fields": {
      "statuscategorychangedate": "2026-03-14T11:05:33.530+0100",
      "issuetype": {
        "self": "https://hosseinzahed.atlassian.net/rest/api/2/issuetype/10001",
        "id": "10001",
        "description": "Submit a request or report a problem.",
        "iconUrl": "https://hosseinzahed.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10677?size=medium",
        "name": "Submit a request or incident",
        "subtask": false,
        "avatarId": 10677,
        "hierarchyLevel": 0
      },
      "timespent": null,
      "customfield_10030": null,
      "project": {
        "self": "https://hosseinzahed.atlassian.net/rest/api/2/project/10000",
        "id": "10000",
        "key": "GTS",
        "name": "General Ticketing System",
        "projectTypeKey": "service_desk",
        "simplified": false,
        "avatarUrls": {
          "48x48": "https://hosseinzahed.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10412",
          "24x24": "https://hosseinzahed.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10412?size=small",
          "16x16": "https://hosseinzahed.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10412?size=xsmall",
          "32x32": "https://hosseinzahed.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/10412?size=medium"
        }
      },
      "customfield_10031": null,
      "customfield_10032": null,
      "fixVersions": [],
      "customfield_10033": null,
      "statusCategory": {
        "self": "https://hosseinzahed.atlassian.net/rest/api/2/statuscategory/2",
        "id": 2,
        "key": "new",
        "colorName": "blue-gray",
        "name": "New"
      },
      "customfield_10078": null,
      "customfield_10034": [],
      "aggregatetimespent": null,
      "customfield_10112": [],
      "resolution": null,
      "customfield_10035": null,
      "customfield_10079": null,
      "customfield_10036": null,
      "customfield_10027": null,
      "customfield_10028": null,
      "customfield_10029": null,
      "resolutiondate": null,
      "workratio": -1,
      "lastViewed": null,
      "watches": {
        "self": "https://hosseinzahed.atlassian.net/rest/api/2/issue/GTS-5/watchers",
        "watchCount": 0,
        "isWatching": false
      },
      "created": "2026-03-14T11:05:32.841+0100",
      "customfield_10020": null,
      "customfield_10021": null,
      "customfield_10022": null,
      "priority": {
        "self": "https://hosseinzahed.atlassian.net/rest/api/2/priority/3",
        "iconUrl": "https://hosseinzahed.atlassian.net/images/icons/priorities/medium_new.svg",
        "name": "Medium",
        "id": "3"
      },
      "customfield_10023": null,
      "customfield_10024": null,
      "customfield_10025": null,
      "customfield_10026": null,
      "labels": [],
      "customfield_10016": null,
      "customfield_10017": null,
      "customfield_10019": "0|i00013:",
      "timeestimate": null,
      "aggregatetimeoriginalestimate": null,
      "versions": [],
      "issuelinks": [],
      "assignee": null,
      "updated": "2026-03-14T11:05:32.841+0100",
      "status": {
        "self": "https://hosseinzahed.atlassian.net/rest/api/2/status/10000",
        "description": "This was auto-generated by Jira Service Management during workflow import",
        "iconUrl": "https://hosseinzahed.atlassian.net/images/icons/status_generic.gif",
        "name": "To Do",
        "id": "10000",
        "statusCategory": {
          "self": "https://hosseinzahed.atlassian.net/rest/api/2/statuscategory/2",
          "id": 2,
          "key": "new",
          "colorName": "blue-gray",
          "name": "New"
        }
      },
      "components": [],
      "timeoriginalestimate": null,
      "description": "Yaw brake safety feedback fluctuates during idle operation. System occasionally flags unsafe condition and requests manual verification.",
      "customfield_10010": {
        "_links": {
          "jiraRest": "https://hosseinzahed.atlassian.net/rest/api/2/issue/10069",
          "web": "https://hosseinzahed.atlassian.net/servicedesk/customer/portal/1/GTS-5",
          "agent": "https://hosseinzahed.atlassian.net/browse/GTS-5",
          "self": "https://hosseinzahed.atlassian.net/rest/servicedeskapi/request/10069"
        },
        "requestType": {
          "_expands": ["field"],
          "id": "1",
          "_links": {
            "self": "https://hosseinzahed.atlassian.net/rest/servicedeskapi/servicedesk/1/requesttype/1"
          },
          "name": "Submit a request or incident",
          "description": "Submit a request or report a problem.",
          "helpText": "",
          "defaultName": "Submit a request or incident",
          "issueTypeId": "10001",
          "serviceDeskId": "1",
          "portalId": "1",
          "groupIds": ["1"],
          "icon": {
            "id": "10540",
            "_links": {
              "iconUrls": {
                "48x48": "https://hosseinzahed.atlassian.net/rest/api/2/universal_avatar/view/type/SD_REQTYPE/avatar/10540?size=large",
                "24x24": "https://hosseinzahed.atlassian.net/rest/api/2/universal_avatar/view/type/SD_REQTYPE/avatar/10540?size=small",
                "16x16": "https://hosseinzahed.atlassian.net/rest/api/2/universal_avatar/view/type/SD_REQTYPE/avatar/10540?size=xsmall",
                "32x32": "https://hosseinzahed.atlassian.net/rest/api/2/universal_avatar/view/type/SD_REQTYPE/avatar/10540?size=medium"
              }
            }
          }
        },
        "currentStatus": {
          "status": "To Do",
          "statusCategory": "NEW",
          "statusDate": {
            "iso8601": "2026-03-14T11:05:32+0100",
            "jira": "2026-03-14T11:05:32.841+0100",
            "friendly": "Today 11:05 AM",
            "epochMillis": 1773482732841
          }
        }
      },
      "customfield_10014": null,
      "timetracking": {},
      "customfield_10015": null,
      "customfield_10005": null,
      "customfield_10006": null,
      "security": null,
      "customfield_10007": null,
      "customfield_10008": null,
      "customfield_10009": null,
      "aggregatetimeestimate": null,
      "attachment": [],
      "summary": "Yaw brake safety status unstable",
      "creator": {
        "self": "https://hosseinzahed.atlassian.net/rest/api/2/user?accountId=712020%3A0e19ca7f-286b-4b22-9d55-a1afb44ccecd",
        "accountId": "712020:0e19ca7f-286b-4b22-9d55-a1afb44ccecd",
        "avatarUrls": {
          "48x48": "https://secure.gravatar.com/avatar/f2641f1938ab5186db38aadc22ea8be5?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHZ-5.png",
          "24x24": "https://secure.gravatar.com/avatar/f2641f1938ab5186db38aadc22ea8be5?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHZ-5.png",
          "16x16": "https://secure.gravatar.com/avatar/f2641f1938ab5186db38aadc22ea8be5?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHZ-5.png",
          "32x32": "https://secure.gravatar.com/avatar/f2641f1938ab5186db38aadc22ea8be5?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHZ-5.png"
        },
        "displayName": "Hossein Zahed",
        "active": true,
        "timeZone": "Europe/Copenhagen",
        "accountType": "atlassian"
      },
      "subtasks": [],
      "customfield_10040": null,
      "customfield_10041": null,
      "reporter": {
        "self": "https://hosseinzahed.atlassian.net/rest/api/2/user?accountId=712020%3A0e19ca7f-286b-4b22-9d55-a1afb44ccecd",
        "accountId": "712020:0e19ca7f-286b-4b22-9d55-a1afb44ccecd",
        "avatarUrls": {
          "48x48": "https://secure.gravatar.com/avatar/f2641f1938ab5186db38aadc22ea8be5?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHZ-5.png",
          "24x24": "https://secure.gravatar.com/avatar/f2641f1938ab5186db38aadc22ea8be5?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHZ-5.png",
          "16x16": "https://secure.gravatar.com/avatar/f2641f1938ab5186db38aadc22ea8be5?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHZ-5.png",
          "32x32": "https://secure.gravatar.com/avatar/f2641f1938ab5186db38aadc22ea8be5?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FHZ-5.png"
        },
        "displayName": "Hossein Zahed",
        "active": true,
        "timeZone": "Europe/Copenhagen",
        "accountType": "atlassian"
      },
      "customfield_10043": null,
      "customfield_10044": null,
      "aggregateprogress": { "progress": 0, "total": 0 },
      "customfield_10001": null,
      "customfield_10002": [],
      "customfield_10003": null,
      "customfield_10004": null,
      "customfield_10038": null,
      "customfield_10039": null,
      "environment": null,
      "duedate": null,
      "progress": { "progress": 0, "total": 0 },
      "votes": {
        "self": "https://hosseinzahed.atlassian.net/rest/api/2/issue/GTS-5/votes",
        "votes": 0,
        "hasVoted": false
      }
    }
  },
  "changelog": {
    "id": "10072",
    "items": [
      {
        "field": "summary",
        "fieldtype": "jira",
        "fieldId": "summary",
        "from": null,
        "fromString": null,
        "to": null,
        "toString": "Yaw brake safety status unstable"
      },
      {
        "field": "Status",
        "fieldtype": "jira",
        "fieldId": "status",
        "from": null,
        "fromString": null,
        "to": "10000",
        "toString": "To Do"
      },
      {
        "field": "priority",
        "fieldtype": "jira",
        "fieldId": "priority",
        "from": null,
        "fromString": null,
        "to": "3",
        "toString": "Medium"
      },
      {
        "field": "reporter",
        "fieldtype": "jira",
        "fieldId": "reporter",
        "from": null,
        "fromString": null,
        "to": "712020:0e19ca7f-286b-4b22-9d55-a1afb44ccecd",
        "toString": "Hossein Zahed",
        "tmpFromAccountId": null,
        "tmpToAccountId": "712020:0e19ca7f-286b-4b22-9d55-a1afb44ccecd"
      },
      {
        "field": "description",
        "fieldtype": "jira",
        "fieldId": "description",
        "from": null,
        "fromString": null,
        "to": null,
        "toString": "Yaw brake safety feedback fluctuates during idle operation. System occasionally flags unsafe condition and requests manual verification."
      }
    ]
  }
}

####

POST https://prod-31.swedencentral.logic.azure.com:443/workflows/b50b71d8f71e44cba5dde133e7e6851c/triggers/When_an_HTTP_request_is_received/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2FWhen_an_HTTP_request_is_received%2Frun&sv=1.0&sig=z5gr7dFyO0kiys-5RCKXpU58Q0I_DJ-sNdbepURfAsU
Content-Type: application/json

{
"ticket_id": "TSWSUP-10724",
"summary": "Client EDF Toolkit license has incorrect IP address for their wind Turbines",
"description": "Hi TSW support, Client EDF have toolkit license. However they did not notice initially that the IP address is incorrect. Due to this when an issue arose with their 3rd party system, they were unable to utilise toolkit. Customer query: Our issue is we have a connection issue with Toolkit and it seems our license on our laptop is different to the license we are using on bastion. We have always been connecting via the bastion license remotely so hadn’t noticed this issue until today. The local device toolkit license has all of Fallago's old IP details as per below snip. The customer has not been able to use their toolkit since the 13/01/2026."
}